### ISSUE TITLE
Allow use of encrypted JWT

### ISSUE THREAD

**Issue by KarlGallagher** [Dash-Industry-Forum/Guidelines-Security#3]
The current proposed guidelines only allow for use of integrity checking / digital signing to protect token contents.

It is possible that private data may be included in tokens (depending on DRM/License server implementation) - this could be legitimate secrets or indeed just any data that needs to be private (maybe GDPR related)

The guidelines should allow for use of one of the AES authenticated encryption cipher modes specified in the JWE (JSON Web Encryption) RFC : https://tools.ietf.org/html/rfc7516

**Comment by sandersaares** [comment]
It is important to make a distinction here because while closely related, JSON Web Encryption (JWE) and JSON Web Signatures (JWS) are independent and unintegrated data formats, with JSON Web Token (JWT) being a specialization of the latter. In other words, the authorization token format is JSON Web Token, which does not permit encryption, only validation. 

However, we do allow any custom fields to be defined by the license server. Inside the custom properties of the JWT (whether in the header or body), using encryption is perfectly legal. The encrypted data may be serialized in JWE format or in some other format (as determined by the license server protocol).

I will try make a PR that clarifies this.
